<?php

declare(strict_types=1);

namespace App\Services\Knowledge;

use App\Enums\KnowledgeStatus;
use App\Models\Team;
use App\Models\TeamKnowledgeChunk;

/**
 * Brute-force cosine similarity search scoped to a single team.
 *
 * We deliberately skip native vector indexes here: MySQL 8 OSS lacks an
 * ANN index and pgvector would require a full engine swap. For the
 * per-team dataset size we expect (hundreds to low thousands of chunks),
 * an in-memory scan is simpler, predictable, and keeps data-locality
 * tight — one table query, one PHP loop, no external moving parts.
 */
class KnowledgeSearchService
{
    public function __construct(
        private readonly EmbeddingService $embeddings,
    ) {}

    /**
     * @return array<int, array{
     *     chunk_id: int,
     *     knowledge_id: int,
     *     title: string,
     *     heading_path: ?string,
     *     content: string,
     *     score: float,
     * }>
     */
    public function search(Team $team, string $query, int $limit = 5): array
    {
        $query = trim($query);
        if ($query === '') {
            return [];
        }

        $embedded = $this->embeddings->embed([$query]);
        if ($embedded['vectors'] === []) {
            return [];
        }

        $queryVector = $embedded['vectors'][0];
        $model = $embedded['model'];

        // Only compare against chunks generated by the same embedding
        // model — mixing models means mixing coordinate systems and
        // cosine similarity becomes meaningless. Additionally require
        // the parent knowledge entry to still be published: even though
        // the observer clears chunks synchronously on status change, a
        // defence-in-depth join prevents leaked results if a chunk row
        // ever outlives its retraction (e.g. a partial DB failure).
        $chunks = TeamKnowledgeChunk::query()
            ->where('team_id', $team->id)
            ->where('embedding_model', $model)
            ->whereHas('knowledge', fn ($q) => $q->where('status', KnowledgeStatus::Published->value))
            ->with(['knowledge:id,title,slug,status'])
            ->get(['id', 'knowledge_id', 'chunk_index', 'heading_path', 'content', 'embedding']);

        $scored = [];
        foreach ($chunks as $chunk) {
            $score = $this->cosine($queryVector, $chunk->embedding);
            // Belt-and-braces: skip if the parent entry is missing or
            // not published. The whereHas above already filters these
            // out at the DB level; this second check catches any in-memory
            // drift between the query and the rendering loop.
            $knowledge = $chunk->knowledge;
            if ($knowledge === null) {
                continue;
            }
            if (($knowledge->status instanceof KnowledgeStatus
                    ? $knowledge->status
                    : KnowledgeStatus::tryFrom((string) $knowledge->status)) !== KnowledgeStatus::Published) {
                continue;
            }

            $scored[] = [
                'chunk_id' => $chunk->id,
                'knowledge_id' => $chunk->knowledge_id,
                'title' => (string) $knowledge->title,
                'slug' => (string) $knowledge->slug,
                'heading_path' => $chunk->heading_path,
                'content' => (string) $chunk->content,
                'score' => $score,
            ];
        }

        usort($scored, fn ($a, $b) => $b['score'] <=> $a['score']);

        return array_slice($scored, 0, max(1, $limit));
    }

    /**
     * @param  array<int, float>  $a
     * @param  array<int, float>  $b
     */
    private function cosine(array $a, array $b): float
    {
        $len = min(count($a), count($b));
        if ($len === 0) {
            return 0.0;
        }

        $dot = 0.0;
        $normA = 0.0;
        $normB = 0.0;

        for ($i = 0; $i < $len; $i++) {
            $x = (float) $a[$i];
            $y = (float) $b[$i];
            $dot += $x * $y;
            $normA += $x * $x;
            $normB += $y * $y;
        }

        if ($normA <= 0.0 || $normB <= 0.0) {
            return 0.0;
        }

        return $dot / (sqrt($normA) * sqrt($normB));
    }
}
