<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default AI Provider Names
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the AI providers below should be the
    | default for AI operations when no explicit provider is provided
    | for the operation. This should be any provider defined below.
    |
    */

    'default' => env('AI_DEFAULT_PROVIDER', 'sakura'),
    'default_for_images' => 'gemini',
    'default_for_audio' => 'openai',
    'default_for_transcription' => 'openai',
    'default_for_embeddings' => env('AI_DEFAULT_EMBEDDINGS_PROVIDER', 'sakura'),
    'default_for_reranking' => 'cohere',

    /*
    |--------------------------------------------------------------------------
    | Default Chat Model
    |--------------------------------------------------------------------------
    |
    | The default chat model used when no explicit model is provided to an
    | AI text operation. This is consumed by application code (not the SDK
    | core) and can be overridden via the SAKURA_AI_CHAT_MODEL env var.
    |
    */

    'default_chat_model' => env('SAKURA_AI_CHAT_MODEL', 'gpt-oss-120b'),

    /*
    |--------------------------------------------------------------------------
    | Default Embedding Model
    |--------------------------------------------------------------------------
    |
    | Model identifier passed to the embeddings provider when indexing
    | team knowledge. Doc and query embeddings must share the same model
    | for cosine similarity to be meaningful, so this value is stored on
    | each chunk and the search service only compares chunks generated by
    | the currently active model.
    |
    */

    'embedding_model' => env('AI_EMBEDDING_MODEL', 'multilingual-e5-large'),

    /*
    |--------------------------------------------------------------------------
    | Chat Models
    |--------------------------------------------------------------------------
    |
    | The list of chat models the UI exposes as a per-message selector.
    | Each entry maps the provider-side model identifier to a short label
    | (shown in the selector and message badge) and a short description
    | that explains when to reach for that model. Extend this map to add
    | new models without touching the controller or the Vue components.
    |
    */

    'chat_models' => [
        'gpt-oss-120b' => [
            'label' => 'gpt-oss',
            'description' => 'General purpose (default)',
            // Sakura-hosted gpt-oss advertises 128k context but we stay
            // conservative to leave room for system prompt + completion.
            'max_context_tokens' => 100_000,
        ],
        'llm-jp-3.1-8x13b-instruct4' => [
            'label' => 'llm-jp',
            'description' => 'Japanese-tuned',
            'max_context_tokens' => 32_000,
        ],
        'Qwen3-Coder-480B-A35B-Instruct-FP8' => [
            'label' => 'qwen-coder-480',
            'description' => 'Coding (large)',
            'max_context_tokens' => 128_000,
        ],
        'Qwen3-Coder-30B-A3B-Instruct' => [
            'label' => 'qwen-coder-30',
            'description' => 'Coding (lightweight)',
            // Published upper bound is uncertain; align with gpt-oss as a safe default.
            'max_context_tokens' => 100_000,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Chat History Truncation
    |--------------------------------------------------------------------------
    |
    | Fallback `max_context_tokens` budget when the requested model has no
    | explicit entry in `chat_models` (unknown models). Kept intentionally
    | small so surprising models can't accidentally blow past provider limits.
    |
    */

    'chat_fallback_max_context_tokens' => 32_000,

    /*
    |--------------------------------------------------------------------------
    | Caching
    |--------------------------------------------------------------------------
    |
    | Below you may configure caching strategies for AI related operations
    | such as embedding generation. You are free to adjust these values
    | based on your application's available caching stores and needs.
    |
    */

    'caching' => [
        'embeddings' => [
            'cache' => false,
            'store' => env('CACHE_STORE', 'database'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | AI Providers
    |--------------------------------------------------------------------------
    |
    | Below are each of your AI providers defined for this application. Each
    | represents an AI provider and API key combination which can be used
    | to perform tasks like text, image, and audio creation via agents.
    |
    */

    'providers' => [
        'anthropic' => [
            'driver' => 'anthropic',
            'key' => env('ANTHROPIC_API_KEY'),
            'url' => env('ANTHROPIC_URL', 'https://api.anthropic.com/v1'),
        ],

        'azure' => [
            'driver' => 'azure',
            'key' => env('AZURE_OPENAI_API_KEY'),
            'url' => env('AZURE_OPENAI_URL'),
            'api_version' => env('AZURE_OPENAI_API_VERSION', '2025-04-01-preview'),
            'deployment' => env('AZURE_OPENAI_DEPLOYMENT', 'gpt-4o'),
            'embedding_deployment' => env('AZURE_OPENAI_EMBEDDING_DEPLOYMENT', 'text-embedding-3-small'),
        ],

        'cohere' => [
            'driver' => 'cohere',
            'key' => env('COHERE_API_KEY'),
        ],

        'deepseek' => [
            'driver' => 'deepseek',
            'key' => env('DEEPSEEK_API_KEY'),
            'url' => env('DEEPSEEK_URL', 'https://api.deepseek.com'),
        ],

        'eleven' => [
            'driver' => 'eleven',
            'key' => env('ELEVENLABS_API_KEY'),
        ],

        'gemini' => [
            'driver' => 'gemini',
            'key' => env('GEMINI_API_KEY'),
        ],

        'groq' => [
            'driver' => 'groq',
            'key' => env('GROQ_API_KEY'),
            'url' => env('GROQ_URL', 'https://api.groq.com/openai/v1'),
        ],

        'jina' => [
            'driver' => 'jina',
            'key' => env('JINA_API_KEY'),
        ],

        'mistral' => [
            'driver' => 'mistral',
            'key' => env('MISTRAL_API_KEY'),
            'url' => env('MISTRAL_URL', 'https://api.mistral.ai/v1'),
        ],

        'ollama' => [
            'driver' => 'ollama',
            'key' => env('OLLAMA_API_KEY', ''),
            'url' => env('OLLAMA_URL', 'http://localhost:11434'),
        ],

        'openai' => [
            'driver' => 'openai',
            'key' => env('OPENAI_API_KEY'),
            'url' => env('OPENAI_URL', 'https://api.openai.com/v1'),
        ],

        'openrouter' => [
            'driver' => 'openrouter',
            'key' => env('OPENROUTER_API_KEY'),
            'url' => env('OPENROUTER_URL', 'https://openrouter.ai/api/v1'),
        ],

        'sakura' => [
            // Use the openrouter driver because さくらのAI Engine exposes the
            // OpenAI *Chat Completions* API (`/chat/completions`), not the
            // newer Responses API (`/responses`) that the `openai` driver
            // targets in laravel/ai. The openrouter driver is OpenAI-compatible
            // and hits `chat/completions` with Bearer auth, matching Sakura.
            'driver' => 'openrouter',
            'key' => env('SAKURA_AI_API_KEY'),
            'url' => env('SAKURA_AI_BASE_URL', 'https://api.ai.sakura.ad.jp/v1'),
            'models' => [
                'embeddings' => [
                    // The OpenRouter driver also POSTs `/embeddings`, so
                    // Sakura can serve team-knowledge RAG without a second
                    // provider. Override via env if Sakura's catalog changes.
                    'default' => env('AI_EMBEDDING_MODEL', 'multilingual-e5-large'),
                    'dimensions' => (int) env('SAKURA_AI_EMBEDDING_DIMENSIONS', 1024),
                ],
            ],
        ],

        'voyageai' => [
            'driver' => 'voyageai',
            'key' => env('VOYAGEAI_API_KEY'),
            'url' => env('VOYAGEAI_URL', 'https://api.voyageai.com/v1'),
        ],

        'xai' => [
            'driver' => 'xai',
            'key' => env('XAI_API_KEY'),
            'url' => env('XAI_URL', 'https://api.x.ai/v1'),
        ],
    ],

];
